targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true

builders:
  version_builder:
    import: "package:gagaku/gen_version.dart"
    builder_factories: ["versionBuilderFactory"]
    build_extensions: { ".dart": [".dart_xxx"] }
    auto_apply: all_packages
